homework25
deniszerg/homework pull request #2
Opened 2023-11-08 16:31 UTC by deniszerg

2023-11-08 17:10 UTC, deniszerg commented
ia ne ponimaiy gte iskati oshibki

2023-11-09 10:31 UTC, pod1425 commented
Переместите все файлы по пакетам как сказано в задании

2023-11-09 10:33 UTC, pod1425 requested changes

2023-11-09 10:33 UTC, pod1425 commented on src/homework25/main02.java
Наверно этот класс должен был называться Pen?

2023-11-09 10:33 UTC, pod1425 commented on src/homework25/main01.java
Запутались. Пересмотрите код и конспект урока 25

2023-11-13 14:41 UTC, closed without merging